# vi: set ts=2 sts=2 sw=2 et ft=yaml :
version: '3'
services:
  mariadb:
    image: mariadb:10.3.8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: rundeckdb
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: changeme
    command: ['--connect-timeout=120']
    volumes:
      - dbdata:/var/lib/mysql
  rundeck:
    build: rundeck-ansible
    depends_on:
      - mariadb
    ports:
      - 4440:4440
    links:
      - mariadb
    volumes:
      - ./inventory:/inventory
      - ./realm.properties:/home/rundeck/server/config/realm.properties
      - ./Deploy.aclpolicy:/home/rundeck/etc/Deploy.aclpolicy
      - data:/home/rundeck/server/data
    environment:
      RUNDECK_DATABASE_DRIVER: com.mysql.jdbc.Driver
      RUNDECK_ADMIN_PASSWORD: changeme
      RUNDECK_DATABASE_URL: jdbc:mysql://mariadb/rundeckdb?autoReconnect=true&useSSL=false
      RUNDECK_DATABASE_USERNAME: rundeck
      RUNDECK_DATABASE_PASSWORD: changeme

volumes:
  data:
  dbdata:

